### ISSUE TITLE
1.0.1 Gem Issue

### ISSUE THREAD

**Issue by taylorkrause** [daily-co/daily-ruby#8]
Hey all! Just double checking here.. does loading the 1.0.1 gem work for y'all correctly?

`/Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require': /Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/daily-ruby-1.0.1/lib/daily-ruby/models/room_properties_streaming_endpoints_inner.rb:41: syntax error, unexpected local variable or method, expecting '}' (SyntaxError)
..._path' => :'hls_config['storage']['path']',
...                        ^~~~~~~
/Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/daily-ruby-1.0.1/lib/daily-ruby/models/room_properties_streaming_endpoints_inner.rb:41: syntax error, unexpected local variable or method, expecting `end'
...> :'hls_config['storage']['path']',
...                           ^~~~
/Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/daily-ruby-1.0.1/lib/daily-ruby/models/room_properties_streaming_endpoints_inner.rb:42: syntax error, unexpected local variable or method, expecting `end'
...plate' => :'hls_config['storage']['path_template']',
...                        ^~~~~~~
/Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/daily-ruby-1.0.1/lib/daily-ruby/models/room_properties_streaming_endpoints_inner.rb:42: syntax error, unexpected local variable or method, expecting `end'
...onfig['storage']['path_template']',
...                  ^~~~~~~~~~~~~
/Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/daily-ruby-1.0.1/lib/daily-ruby/models/room_properties_streaming_endpoints_inner.rb:43: syntax error, unexpected local variable or method, expecting `end'
...'hls_config['save_hls_recording']',
...             ^~~~~~~~~~~~~~~~~~
/Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/daily-ruby-1.0.1/lib/daily-ruby/models/room_properties_streaming_endpoints_inner.rb:44: syntax error, unexpected local variable or method, expecting `end'
...ants' => :'hls_config['variants']'
...                       ^~~~~~~~
/Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/daily-ruby-1.0.1/lib/daily-ruby/models/room_properties_streaming_endpoints_inner.rb:45: syntax error, unexpected '}', expecting `end'
      }
      ^
/Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/daily-ruby-1.0.1/lib/daily-ruby/models/room_properties_streaming_endpoints_inner.rb:267: syntax error, unexpected end-of-input, expecting `end'
        from /Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
        from /Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/daily-ruby-1.0.1/lib/daily-ruby.rb:113:in `<main>'
        from /Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
        from /Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/bundler-2.5.1/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
        from /Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/bundler-2.5.1/lib/bundler/runtime.rb:55:in `each'
        from /Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/bundler-2.5.1/lib/bundler/runtime.rb:55:in `block in require'
        from /Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/bundler-2.5.1/lib/bundler/runtime.rb:44:in `each'
        from /Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/bundler-2.5.1/lib/bundler/runtime.rb:44:in `require'
        from /Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/bundler-2.5.1/lib/bundler.rb:187:in `require'
        from /Users/taylorkrause/Desktop/dev/esignatures-percentage-field-fixes/humaniz-app-production/config/application.rb:18:in `<main>'
        from /Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/railties-7.1.2/lib/rails/commands/server/server_command.rb:139:in `block in perform'
        from <internal:kernel>:90:in `tap'
        from /Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/railties-7.1.2/lib/rails/commands/server/server_command.rb:136:in `perform'
        from /Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/thor-1.3.0/lib/thor/command.rb:28:in `run'
        from /Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/thor-1.3.0/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/railties-7.1.2/lib/rails/command/base.rb:178:in `invoke_command'
        from /Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/thor-1.3.0/lib/thor.rb:527:in `dispatch'
        from /Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/railties-7.1.2/lib/rails/command/base.rb:73:in `perform'
        from /Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/railties-7.1.2/lib/rails/command.rb:71:in `block in invoke'
        from /Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/railties-7.1.2/lib/rails/command.rb:149:in `with_argv'
        from /Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/railties-7.1.2/lib/rails/command.rb:69:in `invoke'
        from /Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/railties-7.1.2/lib/rails/commands.rb:18:in `<main>'
        from /Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /Users/taylorkrause/Desktop/dev/esignatures-percentage-field-fixes/humaniz-app-production/bin/rails:9:in `<top (required)>'
        from /Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/spring-4.1.3/lib/spring/client/rails.rb:28:in `load'
        from /Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/spring-4.1.3/lib/spring/client/rails.rb:28:in `call'
        from /Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/spring-4.1.3/lib/spring/client/command.rb:7:in `call'
        from /Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/spring-4.1.3/lib/spring/client.rb:30:in `run'
        from /Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/spring-4.1.3/bin/spring:49:in `<top (required)>'
        from /Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/spring-4.1.3/lib/spring/binstub.rb:11:in `load'
        from /Users/taylorkrause/.rvm/gems/ruby-3.0.0/gems/spring-4.1.3/lib/spring/binstub.rb:11:in `<top (required)>'
        from /Users/taylorkrause/Desktop/dev/esignatures-percentage-field-fixes/humaniz-app-production/bin/spring:15:in `require'
        from /Users/taylorkrause/Desktop/dev/esignatures-percentage-field-fixes/humaniz-app-production/bin/spring:15:in `<top (required)>'
        from bin/rails:3:in `load'
        from bin/rails:3:in `<main>'`

**Comment by jamsea** [comment]
Hi @taylorkrause I'll take a look at this today 👀

**Comment by jamsea** [comment]
Hi @taylorkrause , this is fixed in 1.0.2 on my end. Could you try updating? If you still run into an issue, could you show me how you're calling daily-ruby?

Thanks! 🙏
